### ISSUE TITLE
support for UE 4.27

### ISSUE THREAD

**Issue by T3KKIE** [getnamo/NodeJs-Unreal#37]
hi, is a version planned for 4.27

**Comment by getnamo** [comment]
It's likely you can recompile the current master build for 4.27 and it should work

**Comment by huwyane** [comment]
Is this working for 4.27?

I get this error when I have the Node component on an actor and try to simulate:
 "Pure virtual function being called while application was running (GlsRunning == 1)."

**Comment by getnamo** [comment]
@huwyane what platform are you trying to run this on? Windows? Mac? Android? Linux? Have any logs of the crash?

**Comment by JonesHong** [comment]
> It's likely you can recompile the current master commit for 4.27 and it should work

I have tried to use 4.26 and 5, but rebuild always get failded.
I bought Socket.IO Client in marketplace. Does it cause any isue?

**Comment by getnamo** [comment]
It shouldn't, project plugins override any marketplace ones of same type. You do need to have a c++ project or hybrid to compile a plugin in the project though, see https://github.com/getnamo/SocketIOClient-Unreal#github

**Comment by JonesHong** [comment]
After following the [direction ](https://allarsblog.com/2015/11/05/converting-bp-project-to-cpp/)in SocketIO-Unreal.

I create a blank project in 4.26 and set plugins (Nodejs-Unreal & SocketIO-Client).
Create a none class in C++.
Build project as "Development Editor" and "Development".
Project can be open in 4.26.
Then I try to switch Unreal Engine version to 4.27.
Open project.
It says need to rebuild, but always get failded around  70%.

Also I try to deleted SocketIO-Client in Plugins.Because I already installed in marketplace.
My thought is that only rebuild Nodejs-Unreal. Yet it still rebuild failed.

What did I do wrong or missing?
I try this tutorial on [YouTube](https://youtu.be/YGHabDYjs6c), but nothing changed.

**Comment by getnamo** [comment]
Made a backport release for UE4.27: 
https://github.com/getnamo/NodeJs-Unreal/releases/tag/v1.1.0. It uses the marketplace version for 4.27 of socket.io (https://github.com/getnamo/SocketIOClient-Unreal/releases/tag/v1.10.0) and had one compile change to work with that matching plugin. I did have to remove the marketplace one to generate the project files for 4.27 but after that it worked as expected.

You should be able to delete the embedded socket.io plugin as well if you're using the marketplace one (but it's untested)

**Comment by getnamo** [comment]
Backport branch for reference: https://github.com/getnamo/NodeJs-Unreal/tree/ue4.27
