### ISSUE TITLE
Virus detected in v1.7.0

### ISSUE THREAD

**Issue by AnimeGarlicoin** [getnamo/NodeJs-Unreal#65]
Windows Defender detected Trojan:Script/Wacatac.B!ml

**Comment by getnamo** [comment]
which file?

**Comment by getnamo** [comment]
I suspect it might have triggered on an old dependency `npm-programmatic` which we don't use since a few years but was left in the `package.json`. Went ahead and removed it and made v1.7.1 release. Let me know if that stopped the trigger warning.

See https://github.com/getnamo/NodeJs-Unreal/releases/tag/v1.7.1

**Comment by AnimeGarlicoin** [comment]
Yes, that solved the issue, thank you.
